


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
#线程池配置
  dtp:
    executors:
      # 线程池1
      - poolName: dtpExecutor1
        corePoolSize: 5
        maximumPoolSize: 10
      # 线程池2
      - poolName: dtpExecutor2
        corePoolSize: 2
        maximumPoolSize: 15

server:
  port: 8888
mybatis:

  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
   map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo





