
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      client-type: lettuce
      port: 6379
      password: 123456
      host: 120.76.243.29

thymeleaf:
    cache: false


server:
  port: 8888
mybatis:

  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
   map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo






