
spring:
  datasource:
    url: jdbc:mysql://120.76.243.29:3306/basic?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      client-type: lettuce
      port: 6379
      password: 123456
      host: 120.76.243.29


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: pushservice-system-web
      auto-offset-reset: earliest
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer



thymeleaf:
    cache: false
binlog:
  mysql:
    host: 120.76.243.29
    port: 3306
    username: root
    password: 12345678
    database: basic

server:
  port: 8080
mybatis:

  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
   map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo






